version: '3'
services:
  web:
    build: .
    ports:
      - 5000:5000
  redis:
    container_name: redis
    image: redis:6.0.6
    ports:
      - 6379:6379
    restart: always
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672